before_install:
  - echo 'Run npm install'
  - npm install 
  - npm install -g webpack-cli
  - which webpack

deploy:
  provider: pages
  local_dir: _site
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master

notifications:
  email: 
    on_success: never
    on_failure: always
